### PR TITLE
feat: add saas.socialShare to schema

### PR DESCRIPTION
**Pull request by chrisvxd**

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
Looks good; for this to take effect, it needs to be added to `config.schema.json`. the `ts` file is just a useful reference that isn't used by the code.

**Comment by transitive-bullshit** [comment]
Will add that on my end before publishing.

**Comment by transitive-bullshit** [comment]
Aaaand nevermind 😄

**Comment by chrisvxd** [comment]
Yeah I thought that but some other bits were missing from the config schema 🤔

**Pull request merged**
